# 基础项目配置
spring:
  jpa:
    hibernate:
      naming:
        #使用自己实现的 命名转换
        physical-strategy: com.ming.base.orm.MyPhysicalNamingStrategy
      # 创建的时候 可以自动创建
      ddl-auto: create
    show-sql: true
  application:
    name: ming-qz
  profiles:
    active: dev
