# dev环境配置  使用本地 mysql   guava做缓存

spring:
  # 关系数据库数据源配置
  # 使用 阿里的  druid 连接池  使用mysql 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/ming?useUnicode=true&characterEncoding=utf-8"
    username: root
    password: ming
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 6000
    time-between-eviction-runs-millis: 6000
    min-evictable-idle-time-millis: 3000
    validation-query: "SELECT 1 FROM DUAL"
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: "stat,wall,log4j"
    connection-properties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000"
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true
  #缓存设置  先采用guava 提供的缓存   可以切换到其他缓存技术 例如redis之类的
  cache:
    type: guava
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    pool:
#     max-idle: 100
#     min-idle: 1
#     max-active: 1000
#     max-wait: -1

quartz:
  properties-config-location: classpath:/config/application-quatrz.properties
# log 配置  只打印 错误和警告 方便排错
logging:
  file: logs/mingqz.log
  level:
   - error
   - warn

