info:
  app:
    name: eureka1
server:
  port: 10001
spring:
  application:
    name: eureka1
eureka:
  instance:
    hostname: eureka-server1
  client:
    # 不向注册中心注册 自己
    #register-with-eureka: false
    # 不检索服务
    #fetch-registry: false
    # 默认服务路径
    serviceUrl:
      defaultZone: http://localhost:10002/eureka/

