DROP TABLE user;
CREATE TABLE user (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(100),
  name     VARCHAR(100),
  age      INT,
  balance  DECIMAL(10, 2),
  PRIMARY KEY (id)
);