server:
  port: 10002
spring:
  application:
    name: eureka-server2
eureka:
  instance:
    hostname: ek2
  client:
    # 不向注册中心注册 自己
    #register-with-eureka: false
    # 不检索服务
    #fetch-registry: false
    # 默认服务路径
    serviceUrl:
      defaultZone: http://127.0.0.1:10001/eureka/