spring:
  application:
    name: turbine
management:
  port: 11000
server:
  port: 11000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
turbine:
  app-config: COMMON
  cluster-name-expression: default
  combine-host-port: true