# default port
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        svn:
          # svn 配置仓库地址
          uri: https://repo.xujiuming.com/svn/ming/trunk/confDir
          # svn 访问账户
          username: ming
          # svn 访问密码
          password: mingpwd
          # 这个设置是访问时候没有带label默认的label  用处不大
          default-label: trunk
  # 使用 svn 作仓库  必须要填写
  profiles:
    active: subversion

# 访问控制
security:
  user:
    name: ming
    password: ming
encrypt:
  # rsa 密钥 设定 使用resources 下的 configServer.keystore
  key-store:
    location: configServer.keystore
    alias: configServer
    #  生成 密钥时候的密码
    password: mingpwd
    # 生成 密钥时候的签名
    secret: mingsecret